version: 2

build:
  os: ubuntu-20.04
  image: latest

sphinx:
  configuration: doc/conf.py

python:
  version: 3.10
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
